- nodeset:
    name: emea-node
    nodes:
      - name: centos1
        label: centos1
         
- nodeset:
    name: nafta-node
    nodes:
      - name: centos2
        label: centos2

        
#- nodeset:
#    name: gate-node
#    nodes:
#     - name: gate
#        label: centos76 

- job:
    name: democbuildjob
    run: playbooks/democbuild.yml
    parent: base

- project:
#    vars:
#      myname: "juhi"
    check_nafta_cpjt:
      jobs:
        - democbuildjob:
            irrelevant-files:
              - .zuul.yaml
              - playbooks
          #  host-vars: 
          #    node2:
        #        jfrog: "http://172.31.20.175:9082"
         #       jfrog_api_token: "AKCp5dK4wtavETSJAiGFMbVRpe7YeGa8WdPzNmzqtvukpUnPdpschfY1RtrZXadQCpSHpAm4d"
            nodeset: nafta-node
