- nodeset:
    name: emea-node
    nodes:
      - name: node
        label: ubuntu-bionic
         
- nodeset:
    name: nafta-node
    nodes:
      - name: node2
        label: centos76

        
- nodeset:
    name: gate-node
    nodes:
      - name: gate
        label: centos76 

- job:
    name: democbuildjob
    run: playbooks/democbuild.yaml
    parent: base

- project:
#    vars:
#      myname: "juhi"
    check_nafta:
      jobs:
        - democbuild:
            host-vars: 
              node2:
                jfrog: "http://172.31.20.175:9082"
                jfrog_api_token: "AKCp5dK4wtavETSJAiGFMbVRpe7YeGa8WdPzNmzqtvukpUnPdpschfY1RtrZXadQCpSHpAm4d"
            nodeset: nafta-node
