- hosts: all
  tasks:
    - debug:
        msg: "running for gameof life demo"
#    - debug: 
#         msg: "{{ emea_jfrog }}"
#    - debug:
#        msg: "{{ nafta_jfrog }}"
        
    - name: "Deleted the workspace dir before build"
      shell: |
            rm -rf ~/work
      register: clean_output
      
    - name: Clone git repo
      git:
        repo: https://github.com/zuul-hcl-org/sample-c-pjt.git
        dest: ~/work/sample-c-pjt
      when: clean_output is succeeded
      
    - name: Build sample project
      shell: |
            cd ~/work/sample-c-pjt
            rm -rf build
            mkdir build
            cd build
            cmake ..
            make            
      register: build_status
      
    - name: Push artifacts to jfrog repository
      uri:
        url: "{{ jfrog }}/artifactory/generic-local/binary_{{ zuul.build }}"
        #when: zuul_location in emea
        validate_certs: no
        method: PUT
        headers:
          X-JFrog-Art-Api: "{{ jfrog_api_token }}"
        src: ~/work/sample-c-pjt/build/binary
        status_code: 201
        remote_src: yes
      when: build_status is succeeded
